apiVersion: v1
kind: ConfigMap
metadata:
  name: blufountain-burial-society-backend-config
  namespace: blufountain-burial-society-backend

data:
  DB_URL: "jdbc:postgresql://insurehub-db-server.postgres.database.azure.com:5432/blufountain_burial_society"
  DB_USER: "insurehub_admin"

  DB_PASS: "Password123!"
