apiVersion: apps/v1
kind: Deployment
metadata:
  name: blufountain-burial-society-backend-deployment
  namespace: blufountain
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blufountain-burial-society-backend
  template:
    metadata:
      labels:
        app: blufountain-burial-society-backend
    spec:
      containers:
      - name: blufountain-burial-society-backend
        image: kaributechsworkflow/blufountain-burial-society-backend:6546352c1bb734dc2f002823c2edee672a666a47
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: blufountain-burial-society-backend-config











