apiVersion: v1
kind: ConfigMap
metadata:
  name: blufountain-burial-society-backend-config
  namespace: blufountain

data:
   DB_URL: "jdbc:postgresql://195.201.150.91:5432/blufountain_burial_society"
   DB_USER: "postgres"
   DB_PASS: "Blufountain2026!"



