apiVersion: v1
kind: ConfigMap
metadata:
  name: blufountain-burial-society-backend-config
  namespace: blufountain

data:
  spring.datasource.url=jdbc:postgresql://195.201.150.91:5432/blufountain_burial_society
  spring.datasource.username=postgres
  spring.datasource.password=Blufountain2026!

