apiVersion: apps/v1
kind: Deployment
metadata:
  name: blufountain-burial-society-backend
  namespace: blufountain
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blufountain-burial-society-backend
  template:
    metadata:
      labels:
        app: blufountain-burial-society-backend

    spec:
      containers:
      - name: blufountain-burial-society-backend
        image: kaributechsworkflow/blufountain-burial-society-backend:4c123c9797fa154264a43081dcbed2883fe47ef9
        ports:

        - containerPort: 8080
