apiVersion: v1
kind: Service
metadata:
  name: blufountain-burial-society-backend
  namespace: blufountain-burial-society-backend
spec:
  type: NodePort
  selector:
    app: blufountain-burial-society-backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30455